### ISSUE TITLE
chickenpaintの問題に対処するcss/jsは外部化すべき

### ISSUE THREAD

**Issue by sakots** [satopian/poti-kaini#5]
各paint.htmlの

```css
:not(input),#chickenpaint-parent :not(input){
-moz-user-select: none;
-webkit-user-select: none;
-ms-user-select: none;
user-select: none;
}
```

```js
function load() {
document.addEventListener("dblclick", function(e){ e.preventDefault();}, { passive: false });
}
window.onload = load;
```

今後chickenpaint側で対処された場合や、他の不具合が出た場合のためにも外部ファイル化すべきだと思うのですがどうでしょうか。
